# Perform BIG-IP failover.
#
# Sample cli usage:
# ansible-playbook lb_failover.yml -i hosts
#
# Sample crontab usage:
# Run at 7pm on 15/11:
#SHELL=/bin/bash
#0 19 15 11 * cd /home/socadmin/F5-env/ansible2.12.3 && source bin/activate && bin/ansible-playbook playbooks/lb_failover.yml > /opt/ansible/logs/lb_failover.log 2>&1

---
- name: F5 BIG-IP Perform Failover
  hosts: F5-Lab
  gather_facts: False
  vars:

    provider:
      password: "{{ ansible_ssh_pass }}"
      server: "{{ ansible_host }}"
      user: "{{ ansible_user }}"
      validate_certs: False

  tasks:
  
    - name: Register failover state
      command: cat /var/prompt/ps1
      register: failover_state
    
    - block:

      - name: Perform failover
        command: tmsh run sys failover standby

      when: "'Active' in failover_state.stdout"
...