# Tested versions: 15.1.6

---
- name: F5 BIG-IP Upgrade DNS Standalone
  hosts: hosts
  gather_facts: False
  any_errors_fatal: true
  # Run play on one host at a time:
  serial: 1
  vars:

    provider:
      password: "{{ ansible_ssh_pass }}"
      server: "{{ ansible_host }}"
      user: "{{ ansible_user }}"
      validate_certs: False

  tasks:

    - name: Register Partitions
      shell: tmsh list auth partition | grep partition | awk '{print $3}'
      register: partitions

    - name: Register date on BIG-IP
      command: date "+%F"
      register: date

    - name: Register gtm sync-group name
      shell: tmsh list gtm global-settings general synchronization-group-name | grep name | awk '{print $2}'
      register: gtm_group

    # Check if vs discovery is enabled on gtm in question, then disable or set enabled (no delete).
    # Task not required for lb-cm devices.
    
    - block:
      # Disable gtm sync and rename sync group.
      - name: Disabling gtm sync and renaming sync group
        shell: |
          tmsh modify gtm global-settings general synchronization no
          tmsh modify gtm global-settings general synchronize-zone-files no
          tmsh modify gtm global-settings general synchronization-group-name Upgrading

      - name: Save running configuration
        bigip_config:
          save: yes
          provider: "{{ provider }}"
        delegate_to: localhost
      
      - name: Register current boot volume name
        shell: tmsh show sys software status | grep yes | awk '{print $1}'
        register: cur_vol

      - name: Gather pre-upgrade config facts
        bigip_device_info:
          partition: "{{ item }}"
          gather_subset:
            - gtm-servers
            - self-ips
            - vlans
          provider: "{{ provider }}"
        loop: "{{ partitions.stdout_lines }}"
        register: f5_info
        delegate_to: localhost

      - name: Pre-upgrade parse
        set_fact:
          startvirtstats: "{{ f5_info.results | map(attribute='gtm_servers') | flatten
            | items2dict(key_name='full_path', value_name='product') }}"
          startselfstats: "{{ f5_info.results | map(attribute='self_ips') | flatten
            | items2dict(key_name='full_path', value_name='vlan') }}"
          startvlanstats: "{{ f5_info.results | map(attribute='vlans') | flatten
            | items2dict(key_name='full_path', value_name='tag') }}"
      
      # Comment out this task if no connectivity to callhome or activate.f5.com.
      - name: Reactivate License
        shell: SOAPLicenseClient --basekey $(perl -ane 'print $F[3] if /^Registration Key/' /config/bigip.license)
      
      - name: Wait for configuration to finish loading
        wait_for:
          timeout: 120
        delegate_to: localhost
      
      - name: Download a new UCS
        bigip_ucs_fetch:
          async_timeout: 1800
          src: "{{ inventory_hostname + '-' + date.stdout +  '-backup.ucs' }}"
          dest: "{{ '/backups/' + inventory_hostname + '-' + date.stdout +  '-backup.ucs' }}"
          provider: "{{ provider }}"
        delegate_to: localhost
      
      - name: Upload upgrade image
        bigip_software_image:
          image: "{{ '/images/' + upgrade_iso }}"
          provider: "{{ provider }}"
        delegate_to: localhost
      
      - name: Wait for image to become available
        wait_for:
          timeout: 30
        delegate_to: localhost
      
      - name: Get available volume number to use
        script: /scripts/get_vol_number.bash
        register: vol
      
      - name: Install BIG-IP software
        bigip_software_install:
          image: "{{ upgrade_iso }}"
          state: activated
          volume: "{{ vol.stdout }}"
          provider: "{{ provider }}"
        delegate_to: localhost

      - name: Allow some time for health monitoring to finish
        wait_for:
          # The wait_for timeout should be more than the maximum health monitor timeout.
          timeout: 300
        delegate_to: localhost
      
      - block:
          - name: Gather post-upgrade config facts
            bigip_device_info:
              partition: "{{ item }}"
              gather_subset:
                - gtm-servers
                - self-ips
                - vlans
              provider: "{{ provider }}"
            loop: "{{ partitions.stdout_lines }}"
            register: f5_info
            delegate_to: localhost

          - name: Post-upgrade parse
            set_fact:
              endvirtstats: "{{ f5_info.results | map(attribute='gtm_servers') | flatten
                | items2dict(key_name='full_path', value_name='product') }}"
              endselfstats: "{{ f5_info.results | map(attribute='self_ips') | flatten
                | items2dict(key_name='full_path', value_name='vlan') }}"
              endvlanstats: "{{ f5_info.results | map(attribute='vlans') | flatten
                | items2dict(key_name='full_path', value_name='tag') }}"
          
          - name: Check GTM Servers
            assert:
              that:
                - item.value == endvirtstats[item.key]
              fail_msg: "gtm server '{{ item.key }}' state changed from '{{ item.value }}' to '{{ endvirtstats[item.key] }}'"
              success_msg: "{{ item.key }} state unchanged"
              quiet: yes
            loop: "{{ startvirtstats|dict2items }}"
            loop_control:
              label: "{{ item.key }}"

          - name: Check Self-IPs
            assert:
              that:
                - item.value == endselfstats[item.key]
              fail_msg: "Self IP '{{ item.key }}' state changed from '{{ item.value }}' to '{{ endselfstats[item.key] }}'"
              success_msg: "{{ item.key }} state unchanged"
              quiet: yes
            loop: "{{ startselfstats|dict2items }}"
            loop_control:
              label: "{{ item.key }}"

          - name: Check VLANs
            assert:
              that:
                - item.value == endvlanstats[item.key]
              fail_msg: "VLAN '{{ item.key }}' state changed from '{{ item.value }}' to '{{ endvlanstats[item.key] }}'"
              success_msg: "{{ item.key }} state unchanged"
              quiet: yes
            loop: "{{ startvlanstats|dict2items }}"
            loop_control:
              label: "{{ item.key }}"

        rescue:
          - name: Post checks failed, rolling back and exiting play
            command: tmsh reboot volume "{{ cur_vol.stdout }}"
          
          - meta: end_play
    
    - name: Add device into gtm sync-group
      command: tmsh modify gtm global-settings general synchronization-group-name "{{ gtm_group.stdout }}" 

    - name: Enable gtm sync
      shell: |
        tmsh modify gtm global-settings general synchronize-zone-files yes
        tmsh modify gtm global-settings general synchronization yes
        tmsh save sys config
...